# Function to wrangle the population data. Run before wrangling population data
# in wrangle-data.R file.
wrangle_pop <- function(population)
{
  population <- setNames(population, population[1,])
  population <- population[-1,-1]
  population <- population[,!str_detect(names(population), "Margin of Error")]
  population <- population[,!str_detect(names(population), "Percent")]
  population <- population[,!str_detect(names(population), "PERCENT")]
  population <- population[,-seq(2,4)]
  population <- population[,-c(6,7,9)]
  population <- population[,-c(21,27,41,46,70,90)]
  population <- setNames(population, c("County", 
                                       "Over16_Employed",
                                       "Over16_Unemployed",
                                       "Over16_ArmedForces",
                                       "Over16_NotInLaborForce",
                                       "Over16_Female_Population",
                                       "Over16_Female_LaborForce",
                                       "Over16_Female_Employed",
                                       "Child-6_SingleWorkingParent_NumHouseholds",
                                       "Child-6_BothWorkingParents_NumHouseholds",
                                       "Child6-17_SingleWorkingParents_NumHouseholds",
                                       "Child6-17_BothWorkingParents_NumHouseholds",
                                       "Commuters_NumWorkers",
                                       "Commuters_DroveAlone",
                                       "Commuters_Carpooled",
                                       "Commuters_PublicTransport",
                                       "Commuters_Walked",
                                       "Commuters_Other",
                                       "Commuters_AtHome",
                                       "Commuters_MeanTravelTime",
                                       "Occupation_Management_Business_Science_Arts",
                                       "Occupation_Service",
                                       "Occupation_Sales_Office",
                                       "Occupation_NaturalResources_Construction_Maintenance",
                                       "Occupation_Production_Transportation_MaterialMovement",
                                       "Industry_Agriculture_Forestry_Fishing-Hunting_Mining",
                                       "Industry_Construction",
                                       "Industry_Manufacturing",
                                       "Industry_Wholesale",
                                       "Industry_Retail",
                                       "Industry_Transportation_Warehousing_Utilities",
                                       "Industry_Information",
                                       "Industry_Finance-Insurance_RealEstate_Rental-Leasing",
                                       "Industry_Professional_Scientific_Management_Administrative_WasteManagement",
                                       "Industry_Education_HealthCare_SocialAssistance",
                                       "Industry_Arts_Entertainment_Recreation_Accomodation_FoodServices",
                                       "Industry_Other_Not_Public_Administration",
                                       "Industry_Public_Administration",
                                       "Class_Private_Salary",
                                       "Class_Government",
                                       "Class_SelfEmployed",
                                       "Class_Unpaid",
                                       "Income_-10,000",
                                       "Income_10,000-14,999",
                                       "Income_15,000-24,999",
                                       "Income_25,000-34,999",
                                       "Income_35,000-49,999",
                                       "Income_50,000-74,999",
                                       "Income_75,000-99,999",
                                       "Income_100,000-149,999",
                                       "Income_150,000-199,999",
                                       "Income_200,000+",
                                       "Income_Median",
                                       "Income_Mean",
                                       "Benefits_Median_Earnings",
                                       "Benefits_Mean_Earnings",
                                       "Benefits_Median_SocialSecurity",
                                       "Benefits_Mean_SocialSecurity",
                                       "Benefits_Median_RetirementIncome",
                                       "Benefits_Mean_RetirementIncome",
                                       "Benefits_Median_SupplementatlSecurity",
                                       "Benefits_Mean_SupplementalSecurity",
                                       "Benefits_Median_CashPublicAssistance",
                                       "Benefits_Mean_CashPublicAssistance",
                                       "Benefits_FoodStamps",
                                       "Income_Family_-10,000",
                                       "Income_Family_10,000-14,999",
                                       "Income_Family_14,000-24,999",
                                       "Income_Family_25,000-34,999",
                                       "Income_Family_35,000-49,999",
                                       "Income_Family_50,000-74,999",
                                       "Income_Family_75,000-99,999",
                                       "Income_Family_100,000-149,999",
                                       "Income_Family_150,000-199,999",
                                       "Income_Family_200,000+",
                                       "Income_Family_MedianIncome",
                                       "Income_Family_MeanIncome",
                                       "Income_Family_PerCapitaIncome",
                                       "Income_NonFamily_NumHouseholds",
                                       "Income_NonFamily_MedianIncome",
                                       "Income_NonFamily_MeanIncome",
                                       "Income_Workers_MedianEarnings",
                                       "Income_MaleWorkers_MedianEarnings",
                                       "Income_FemaleWorkers_MedianEarnings",
                                       "HealthInsurance_WithCoverage",
                                       "HealthInsurance_PrivateInsurance",
                                       "HealthInsurance_PublicInsurance",
                                       "HealthInsurance_NoCoverage",
                                       "HealthInsurance_-19_Population",
                                       "HealthInsurance_-19_NoCoverage",
                                       "HealthInsurance_19-64_Population",
                                       "HealthInsurance_19-64_InLaborForce",
                                       "HealthInsurance_19-64_Employed",
                                       "HealthInsurance_19-64_Employed_Coverage",
                                       "HealthInsurance_19-64_Employed_PrivateInsurance",
                                       "HealthInsurance_19-64_Employed_PublicInsurance",
                                       "HealthInsurance_19-64_Employed_NoCoverage",
                                       "HealthInsurance_19-64_Unemployed",
                                       "HealthInsurance_19-64_Unemployed_Coverage",
                                       "HealthInsurance_19-64_Unemployed_PrivateInsurance",
                                       "HealthInsurance_19-64_Unemployed_PublicInsurance",
                                       "HealthInsurance_19-64_Unemployed_NoCoverage",
                                       "HealthInsurance_19-64_NotInLaborForce",
                                       "HealthInsurance_19-64_NotInLaborForce_Coverage",
                                       "HealthInsurance_19-64_NotInLaborForce_PrivateInsurance",
                                       "HealthInsurance_19-64_NotInLaborForce_PublicInsurance",
                                       "HealthInsurance_19-64_NotInLaborForce_NoCoverage"
  ))
}
